tag: INFRA
section: mcp-servers
servers:
  - name: docker
    description: "Docker container and image management via MCP"
    command: npx
    args: ["-y", "mcp-server-docker"]
    tags: [INFRA]
    category: deployment
    url: "https://github.com/ckreiling/mcp-server-docker"

  - name: kubernetes
    description: "Kubernetes cluster management — pods, deployments, services"
    command: npx
    args: ["-y", "mcp-server-kubernetes"]
    tags: [INFRA]
    category: deployment
    url: "https://github.com/strowk/mcp-k8s-go"
