#!/usr/bin/env node
/**
 * self-check.mjs — ForgeCraft self-consistency check.
 *
 * Scaffolds a fresh project using ForgeCraft's own spec and tags,
 * then compares the generated output against what ForgeCraft itself has.
 *
 * Reports in three categories:
 *   GS GAPS         — generated by scaffold, missing from actual ForgeCraft
 *   USEFUL EXTRAS   — in actual ForgeCraft, not generated by scaffold (innovation)
 *   SCAFFOLD REVIEW — generated structures worth validating for complexity
 *
 * Usage:
 *   npm run self-check
 *   node scripts/self-check.mjs [--verbose]
 */

import { mkdirSync, rmSync, existsSync, readFileSync, readdirSync } from "node:fs";
import { join, relative } from "node:path";
import { tmpdir } from "node:os";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const projectRoot = join(__dirname, "..");
const verbose = process.argv.includes("--verbose");

// ── Load project config ───────────────────────────────────────────────
const yamlText = readFileSync(join(projectRoot, "forgecraft.yaml"), "utf-8");
// Simple YAML key extraction (avoid importing js-yaml from scripts)
function extractYamlList(text, key) {
  const m = text.match(new RegExp(`^${key}:\\s*\\[([^\\]]+)\\]`, "m"));
  if (m) return m[1].split(",").map((s) => s.trim().replace(/['"]/g, ""));
  const block = text.match(new RegExp(`^${key}:\\s*\\n((?:  - .+\\n)*)`, "m"));
  if (block) return block[1].split("\n").map((l) => l.replace(/^  - /, "").trim()).filter(Boolean);
  return [];
}
const tags = extractYamlList(yamlText, "tags");
const tier = (yamlText.match(/^tier:\s*(\S+)/m) || [])[1] || "recommended";

console.log(`\n🔍 ForgeCraft Self-Check`);
console.log(`   Project: forgecraft-mcp`);
console.log(`   Tags:    ${tags.join(", ")}`);
console.log(`   Tier:    ${tier}`);
console.log(`   Actual:  ${projectRoot}\n`);

// ── Build check ───────────────────────────────────────────────────────
const distDir = join(projectRoot, "dist");
if (!existsSync(join(distDir, "tools", "setup-project.js"))) {
  console.error("❌ dist/ not built. Run: npm run build");
  process.exit(1);
}

// ── Import programmatic API ───────────────────────────────────────────
const { setupProjectHandler } = await import("../dist/tools/setup-project.js");

// ── Scaffold into temp dir ────────────────────────────────────────────
const tempDir = join(tmpdir(), `forgecraft-self-check-${Date.now()}`);
mkdirSync(tempDir, { recursive: true });

process.env["VITEST"] = "1"; // suppress git operations

try {
  console.log("📦 Scaffolding fresh project with ForgeCraft's own tags...");

  const prdPath = join(projectRoot, "docs", "PRD.md");
  const specText = existsSync(prdPath) ? readFileSync(prdPath, "utf-8") : undefined;

  // Phase 1
  await setupProjectHandler({
    project_dir: tempDir,
    ...(specText ? { spec_text: specText } : {}),
  });

  // Phase 2
  await setupProjectHandler({
    project_dir: tempDir,
    mvp: false,
    scope_complete: true,
    has_consumers: true,
    tags,
  });

  console.log("✅ Scaffold complete\n");

  // ── Collect artifacts ───────────────────────────────────────────────
  const generated = collectArtifacts(tempDir);
  const actual = collectArtifacts(projectRoot, { excludeDist: true, excludeNode: true });

  // ── Compare ─────────────────────────────────────────────────────────
  const report = compare(generated, actual, tempDir, projectRoot);

  // ── Print report ────────────────────────────────────────────────────
  printReport(report);

} finally {
  rmSync(tempDir, { recursive: true, force: true });
  delete process.env["VITEST"];
}

// ── Artifact collection ───────────────────────────────────────────────

function collectArtifacts(dir, opts = {}) {
  const artifacts = {
    claudeMdSections: [],
    docsFiles: [],
    hookFiles: [],
    standardsFiles: [],
    agentFiles: [],
    gateFiles: [],
    cnts: [],
  };

  // CLAUDE.md sections
  const claudeMdPath = join(dir, "CLAUDE.md");
  if (existsSync(claudeMdPath)) {
    const content = readFileSync(claudeMdPath, "utf-8");
    artifacts.claudeMdSections = (content.match(/^#{1,3} .+$/gm) || [])
      .map((s) => s.trim())
      .filter((s) => s.length > 2);
  }

  // docs/ files
  const docsDir = join(dir, "docs");
  if (existsSync(docsDir)) {
    artifacts.docsFiles = walkDir(docsDir)
      .map((f) => relative(dir, f))
      .filter((f) => !f.includes("node_modules") && !f.includes(".stryker"));
  }

  // .claude/hooks/ files
  const hooksDir = join(dir, ".claude", "hooks");
  if (existsSync(hooksDir)) {
    artifacts.hookFiles = readdirSync(hooksDir)
      .filter((f) => f.endsWith(".sh"))
      .sort();
  }

  // .claude/standards/ files
  const standardsDir = join(dir, ".claude", "standards");
  if (existsSync(standardsDir)) {
    artifacts.standardsFiles = readdirSync(standardsDir)
      .filter((f) => f.endsWith(".md"))
      .sort();
  }

  // .claude/agents/ files
  const agentsDir = join(dir, ".claude", "agents");
  if (existsSync(agentsDir)) {
    artifacts.agentFiles = readdirSync(agentsDir)
      .filter((f) => f.endsWith(".md"))
      .sort();
  }

  // .forgecraft/gates/ files
  const gatesDir = join(dir, ".forgecraft", "gates", "active");
  if (existsSync(gatesDir)) {
    artifacts.gateFiles = walkDir(gatesDir)
      .map((f) => relative(join(dir, ".forgecraft"), f))
      .sort();
  }

  // CNT index
  const cntIndex = join(dir, ".claude", "index.md");
  if (existsSync(cntIndex)) {
    artifacts.cnts = ["index.md"];
  }

  return artifacts;
}

function walkDir(dir) {
  const results = [];
  if (!existsSync(dir)) return results;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...walkDir(full));
    } else {
      results.push(full);
    }
  }
  return results;
}

// ── Comparison ────────────────────────────────────────────────────────

function compare(generated, actual, genDir, actualDir) {
  const report = {
    gsGaps: [],       // in generated, missing from actual
    usefulExtras: [], // in actual, not generated
    scaffoldReview: [], // worth reviewing for over-engineering
    stats: {},
  };

  // CLAUDE.md sections
  const genSections = new Set(generated.claudeMdSections);
  const actSections = new Set(actual.claudeMdSections);

  for (const s of genSections) {
    if (!actSections.has(s)) {
      report.gsGaps.push({ category: "CLAUDE.md section", item: s,
        signal: "scaffold generates this section but ForgeCraft's own CLAUDE.md lacks it" });
    }
  }
  for (const s of actSections) {
    if (!genSections.has(s)) {
      report.usefulExtras.push({ category: "CLAUDE.md section", item: s,
        signal: "ForgeCraft's CLAUDE.md has this; not yet in the standard template" });
    }
  }

  // docs/ files (structural comparison — normalize to basename for matching)
  const genDocsBases = new Set(generated.docsFiles.map((f) => f.replace(/\\/g, "/")));
  const actDocsBases = new Set(actual.docsFiles.map((f) => f.replace(/\\/g, "/")));

  const genDocsNames = new Set(generated.docsFiles.map(basename));
  const actDocsNames = new Set(actual.docsFiles.map(basename));

  for (const f of generated.docsFiles) {
    const name = basename(f);
    if (!actDocsNames.has(name) && !f.includes("session-prompts") && !f.includes("blog")) {
      report.gsGaps.push({ category: "docs/ file", item: f,
        signal: "scaffold creates this; ForgeCraft's own docs/ doesn't have it" });
    }
  }
  for (const f of actual.docsFiles) {
    const name = basename(f);
    if (!genDocsNames.has(name) && !name.startsWith("adr") && !name.startsWith("ADR")) {
      report.usefulExtras.push({ category: "docs/ file", item: f,
        signal: "ForgeCraft has this; not in scaffold output" });
    }
  }

  // Hooks
  const genHooks = new Set(generated.hookFiles);
  const actHooks = new Set(actual.hookFiles);

  for (const h of genHooks) {
    if (!actHooks.has(h)) {
      report.gsGaps.push({ category: "hook", item: h,
        signal: "scaffold installs this hook; ForgeCraft's .claude/hooks/ lacks it" });
    }
  }
  for (const h of actHooks) {
    if (!genHooks.has(h)) {
      report.usefulExtras.push({ category: "hook", item: h,
        signal: "ForgeCraft has this hook; not yet in template" });
    }
  }

  // Standards files
  const genStds = new Set(generated.standardsFiles);
  const actStds = new Set(actual.standardsFiles);

  for (const f of genStds) {
    if (!actStds.has(f)) {
      report.gsGaps.push({ category: "standards file", item: f,
        signal: "scaffold generates this standards file; ForgeCraft's own is missing it" });
    }
  }
  for (const f of actStds) {
    if (!genStds.has(f)) {
      report.usefulExtras.push({ category: "standards file", item: f,
        signal: "ForgeCraft has this standards file; not in template" });
    }
  }

  // Agents
  const genAgents = new Set(generated.agentFiles);
  const actAgents = new Set(actual.agentFiles);

  for (const f of genAgents) {
    if (!actAgents.has(f)) {
      report.gsGaps.push({ category: "agent", item: f,
        signal: "scaffold generates this sub-agent; ForgeCraft's own lacks it" });
    }
  }
  for (const f of actAgents) {
    if (!genAgents.has(f)) {
      report.usefulExtras.push({ category: "agent", item: f,
        signal: "ForgeCraft has this agent; not yet in template" });
    }
  }

  report.stats = {
    gsGaps: report.gsGaps.length,
    usefulExtras: report.usefulExtras.length,
    scaffoldReview: report.scaffoldReview.length,
  };

  return report;
}

function basename(f) {
  return f.replace(/\\/g, "/").split("/").pop();
}

// ── Report printer ────────────────────────────────────────────────────

function printReport(report) {
  const line = "─".repeat(60);
  const date = new Date().toISOString().split("T")[0];

  console.log(`${line}`);
  console.log(`ForgeCraft Self-Check Report — ${date}`);
  console.log(`${line}\n`);

  if (report.gsGaps.length === 0) {
    console.log("✅ GS GAPS — none found\n");
  } else {
    console.log(`❌ GS GAPS (${report.gsGaps.length}) — scaffold generates these; ForgeCraft's own project is missing them`);
    console.log("   These represent places where ForgeCraft enforces standards on clients");
    console.log("   but doesn't apply them to itself.\n");
    const byCategory = groupBy(report.gsGaps, "category");
    for (const [cat, items] of Object.entries(byCategory)) {
      console.log(`   [${cat}]`);
      for (const item of items) {
        console.log(`   • ${item.item}`);
        if (verbose) console.log(`     → ${item.signal}`);
      }
      console.log();
    }
  }

  if (report.usefulExtras.length === 0) {
    console.log("ℹ️  USEFUL EXTRAS — none found\n");
  } else {
    console.log(`🔵 USEFUL EXTRAS (${report.usefulExtras.length}) — ForgeCraft has these; not yet in the standard template`);
    console.log("   These may be good candidates for promotion to the universal template,\n");
    console.log("   or they may be ForgeCraft-specific and should stay here.\n");
    const byCategory = groupBy(report.usefulExtras, "category");
    for (const [cat, items] of Object.entries(byCategory)) {
      console.log(`   [${cat}]`);
      for (const item of items) {
        console.log(`   • ${item.item}`);
        if (verbose) console.log(`     → ${item.signal}`);
      }
      console.log();
    }
  }

  console.log(`${line}`);
  console.log(`Summary: ${report.stats.gsGaps} GS gaps  |  ${report.stats.usefulExtras} useful extras`);
  console.log(`Re-run after each feature sprint: npm run self-check`);
  console.log(`Verbose mode: npm run self-check -- --verbose\n`);
}

function groupBy(items, key) {
  const result = {};
  for (const item of items) {
    const k = item[key];
    if (!result[k]) result[k] = [];
    result[k].push(item);
  }
  return result;
}
