#!/bin/bash
# ──────────────────────────────────────────────────────────────────────
# setup-hooks.sh — Install git pre-commit hooks from .claude/hooks/
#
# Run once after cloning:  bash scripts/setup-hooks.sh
# Or automatically via:    npm install  (prepare script)
#
# What gets installed into .git/hooks/pre-commit:
#   1.  pre-commit-no-temp-files  — block temp/draft/unofficial files
#   2.  pre-commit-secrets        — block accidental credential exposure
#   3.  pre-commit-prod-quality   — anti-pattern scan (mocks, hardcoded URLs)
#   4.  pre-commit-branch-check   — no direct commits to main/master
#   5.  pre-commit-format         — auto-format staged TS/JS files
#   6.  pre-commit-compile        — TypeScript compilation check
#   7.  pre-commit-import-cycles  — circular dependency detection (madge/lint-imports)
#   8.  pre-commit-tdd-check      — TDD RED gate: test-only commits must fail;
#                                   warn on implementation commits without tests
#   9.  pre-commit-test           — run bare tests (skips docs/config-only commits and when src/ staged; see #10)
#   10. pre-commit-coverage       — run tests + enforce coverage thresholds (src/ only)
#   11. pre-commit-audit          — block HIGH/CRITICAL CVEs (npm audit, pip-audit, cargo audit)
#   12. pre-commit-doc-cascade    — advisory: warn when src/ changes lack docs/ touch
# ──────────────────────────────────────────────────────────────────────

set -e

HOOKS_SRC=".claude/hooks"
GIT_HOOKS=".git/hooks"

if [ ! -d ".git" ]; then
  echo "⚠️  Not a git repository root — skipping hook installation."
  exit 0
fi

if [ ! -d "$HOOKS_SRC" ]; then
  echo "⚠️  $HOOKS_SRC not found — skipping hook installation."
  exit 0
fi

mkdir -p "$GIT_HOOKS"

# ── Build composite pre-commit hook ──────────────────────────────────
PRE_COMMIT="$GIT_HOOKS/pre-commit"

cat > "$PRE_COMMIT" << 'EOF'
#!/bin/bash
# Auto-generated by scripts/setup-hooks.sh — do not edit by hand.
# Re-run `bash scripts/setup-hooks.sh` to regenerate.
HOOKS_DIR="$(git rev-parse --show-toplevel)/.claude/hooks"

run_hook() {
  local hook="$1"
  local path="$HOOKS_DIR/$hook"
  if [ -f "$path" ]; then
    bash "$path"
    local exit_code=$?
    if [ $exit_code -ne 0 ]; then
      echo "❌ Hook failed: $hook (exit $exit_code)"
      exit $exit_code
    fi
  fi
}

run_hook "pre-commit-no-temp-files.sh"
run_hook "pre-commit-secrets.sh"
run_hook "pre-commit-prod-quality.sh"
run_hook "pre-commit-branch-check.sh"
run_hook "pre-commit-format.sh"
run_hook "pre-commit-compile.sh"
run_hook "pre-commit-import-cycles.sh"
run_hook "pre-commit-eslint.sh"
run_hook "pre-commit-complexity.sh"
run_hook "pre-commit-tdd-check.sh"
run_hook "pre-commit-test.sh"
run_hook "pre-commit-coverage.sh"
run_hook "pre-commit-audit.sh"
run_hook "pre-commit-doc-cascade.sh"
run_hook "pre-commit-gs-links.sh"

exit 0
EOF

chmod +x "$PRE_COMMIT"

# ── Install commit-msg hook (conventional commit enforcement) ─────────
COMMIT_MSG_HOOK="$GIT_HOOKS/commit-msg"

cat > "$COMMIT_MSG_HOOK" << 'EOF'
#!/bin/bash
# Auto-generated by scripts/setup-hooks.sh — do not edit by hand.
# Re-run `bash scripts/setup-hooks.sh` to regenerate.
HOOKS_DIR="$(git rev-parse --show-toplevel)/.claude/hooks"

run_msg_hook() {
  local hook="$1"
  local path="$HOOKS_DIR/$hook"
  if [ -f "$path" ]; then
    bash "$path" "$2"
    local rc=$?
    if [ $rc -ne 0 ]; then
      echo "❌ Hook failed: $hook (exit $rc)"
      exit $rc
    fi
  fi
}

run_msg_hook "commit-msg.sh"        "$1"
run_msg_hook "commit-msg-cascade.sh" "$1"
exit 0
EOF

chmod +x "$COMMIT_MSG_HOOK"

# ── Install post-commit hook (generators) ────────────────────────────
POST_COMMIT="$GIT_HOOKS/post-commit"

cat > "$POST_COMMIT" << 'EOF'
#!/bin/bash
# Auto-generated by scripts/setup-hooks.sh — do not edit by hand.
HOOKS_DIR="$(git rev-parse --show-toplevel)/.claude/hooks"

run_post_hook() {
  local hook="$1"
  local path="$HOOKS_DIR/$hook"
  [ -f "$path" ] && bash "$path"
  return 0
}

run_post_hook "post-commit-changelog.sh"
run_post_hook "post-commit-complexity-baseline.sh"
exit 0
EOF

chmod +x "$POST_COMMIT"

# ── Install prepare-commit-msg hook (enrichers) ───────────────────────
PREPARE_COMMIT_MSG="$GIT_HOOKS/prepare-commit-msg"

cat > "$PREPARE_COMMIT_MSG" << 'EOF'
#!/bin/bash
# Auto-generated by scripts/setup-hooks.sh — do not edit by hand.
HOOKS_DIR="$(git rev-parse --show-toplevel)/.claude/hooks"
HOOK="$HOOKS_DIR/prepare-commit-msg-usecase.sh"
[ -f "$HOOK" ] && bash "$HOOK" "$1" "$2"
exit 0
EOF

chmod +x "$PREPARE_COMMIT_MSG"

# ── Install pre-push hook ─────────────────────────────────────────────
PRE_PUSH="$GIT_HOOKS/pre-push"

cat > "$PRE_PUSH" << 'PUSHEOF'
#!/bin/bash
# Auto-generated by scripts/setup-hooks.sh — do not edit by hand.
HOOKS_DIR="$(git rev-parse --show-toplevel)/.claude/hooks"

# ── Read stdin once; pass to both checks ──────────────────────────────
PUSH_INPUT=$(cat)

# Block deletion of main/master
while read -r local_ref local_sha remote_ref remote_sha; do
  if [ "$local_sha" = "0000000000000000000000000000000000000000" ]; then
    if echo "$remote_ref" | grep -qE '/(main|master)$'; then
      echo "❌ Deleting remote main/master branch is blocked."
      exit 1
    fi
  fi
done <<< "$PUSH_INPUT"

# Doc-cascade: block pushes where public surface changed without docs
HOOK="$HOOKS_DIR/pre-push-doc-cascade.sh"
if [ -f "$HOOK" ]; then
  echo "$PUSH_INPUT" | bash "$HOOK"
  rc=$?
  if [ $rc -ne 0 ]; then
    echo "❌ Hook failed: pre-push-doc-cascade.sh (exit $rc)"
    exit $rc
  fi
fi

exit 0
PUSHEOF

chmod +x "$PRE_PUSH"

echo "✅ Git hooks installed:"
echo "   .git/hooks/pre-commit         — 15 checks (temp-files, secrets, quality, branch, format, compile, cycles, eslint, complexity, tdd, tests, coverage, audit, doc-cascade, gs-links)"
echo "   .git/hooks/commit-msg         — conventional format + doc-cascade enforcement"
echo "   .git/hooks/prepare-commit-msg — tags commit with touched use case IDs"
echo "   .git/hooks/post-commit        — updates CHANGELOG.md + complexity baseline"
echo "   .git/hooks/pre-push           — blocks branch deletion + doc-cascade enforcement"
echo ""
echo "   Source hooks in:      .claude/hooks/"
echo "   To skip (emergency):  git commit --no-verify"
