/**
 * check-cascade-report: Report formatting and session-prompt writing for check_cascade.
 *
 * Formats cascade results as readable Markdown and writes the initial
 * session prompt stub on first successful cascade completion.
 */

import { existsSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { loadForgeCraftConfig, CONSTITUTION_PATHS } from "./check-cascade-steps.js";
import type { CascadeStep } from "./check-cascade-steps.js";

/**
 * Write docs/session-prompt-initial.md when the cascade first completes.
 * Idempotent — does nothing if the file already exists.
 *
 * @param projectDir - Absolute path to the project root
 */
export function writeInitialSessionPromptIfAbsent(projectDir: string): void {
  const outputPath = join(projectDir, "docs", "session-prompt-initial.md");
  if (existsSync(outputPath)) return;

  const config = loadForgeCraftConfig(projectDir);
  const projectName = config?.projectName ?? "this project";
  const tags = config?.tags ?? [];

  const prdPath = join(projectDir, "docs", "PRD.md");
  const useCasesPath = join(projectDir, "docs", "use-cases.md");
  const constitutionCandidates = CONSTITUTION_PATHS.slice(0, 2).map((p) => join(projectDir, p));
  const constitutionPath = constitutionCandidates.find(existsSync);

  const contextBlock = [
    constitutionPath ? `- ${constitutionPath}` : null,
    existsSync(prdPath) ? `- ${prdPath}` : null,
    existsSync(useCasesPath) ? `- ${useCasesPath}` : null,
  ]
    .filter(Boolean)
    .join("\n");

  const tagLine = tags.length > 0 ? `\nProject tags: ${tags.join(", ")}\n` : "";

  const content = `# Initial Implementation Session Prompt
> Generated by ForgeCraft \`check_cascade\` on cascade completion.
> Delete this file after the first implementation session begins — it is a one-time bootstrap.

---

## Context Load Order

Load these artifacts **before** issuing the implementation prompt:

${contextBlock || "- (No derived artifacts found — run setup_project first)"}

---

## Implementation Prompt

*(Paste everything below this line to the AI assistant)*

---

### Task

You are starting the first implementation session for **${projectName}**.
${tagLine}
Read the PRD and use-cases, then implement the first feature end-to-end following
the architectural constitution. Begin with the domain layer (entities + port interfaces),
then the service layer, then the API/CLI adapter. Apply TDD throughout — write the test
first, then the implementation. Do not proceed to the next layer until tests pass.

### Scope

- Implement the primary use case (UC-001) completely before touching UC-002 or UC-003.
- Infrastructure setup (DB, config, DI container) is in scope only as required by UC-001.
- Do not stub or mock domain logic — implement it fully.

### Execution Loop

1. Read docs/PRD.md → identify UC-001 domain entities and port interfaces
2. Write failing tests for the domain layer
3. Implement domain layer until tests pass
4. Write failing tests for the service layer
5. Implement service layer until tests pass
6. Write failing integration/API tests
7. Implement API/CLI adapter until tests pass
8. Run \`check_cascade\` and \`close_cycle\` before committing

### Acceptance Criteria

- [ ] UC-001 is fully implemented and tested (unit + integration)
- [ ] All tests pass with ≥80% coverage
- [ ] No circular imports (run layer check)
- [ ] SOLID principles applied — each class has a single reason to change
- [ ] \`close_cycle\` reports no blocking gate failures

### Session Close

Before ending this session:
1. Run the full test suite — paste the summary output
2. Update Status.md: what was completed, current state, next steps
3. If a non-obvious architectural decision was made: write an ADR in docs/adrs/

---
\`files_created\`: []
\`next_steps\`: ["Run check_cascade to verify cascade is still complete after this session"]
`;

  mkdirSync(join(projectDir, "docs"), { recursive: true });
  writeFileSync(outputPath, content, "utf-8");
}

/**
 * Format the cascade check results as a readable Markdown report.
 *
 * @param steps - All five cascade step results
 * @param passingCount - Number of PASS steps
 * @param failingCount - Number of FAIL + STUB steps
 * @param noCascadeConfig - Whether no cascade.steps were found in forgecraft.yaml
 * @returns Formatted report string
 */
export function formatReport(
  steps: readonly CascadeStep[],
  passingCount: number,
  failingCount: number,
  noCascadeConfig: boolean,
): string {
  const cascadeComplete = failingCount === 0;
  const statusLabel = cascadeComplete
    ? passingCount === 5 ? "COMPLETE" : "COMPLETE (with warnings)"
    : "BLOCKED";
  const headerIcon = cascadeComplete ? "✅" : "❌";

  let text = `# GS Initialization Cascade Check\n\n`;

  if (noCascadeConfig) {
    text += `> ⚠ No cascade decisions configured. Run \`scaffold\` or use \`set_cascade_requirement\`\n`;
    text += `> to decide which spec artifacts are required for this project.\n`;
    text += `> Defaulting to: all steps required.\n\n`;
  }

  text += `**Status:** ${headerIcon} ${statusLabel}   (${passingCount}/5 steps passing)\n\n`;
  text += `## Steps\n\n`;

  for (const step of steps) {
    const icon =
      step.status === "PASS" ? "✅" :
      step.status === "WARN" ? "⚠️ " :
      step.status === "STUB" ? "⚠ STUB" :
      step.status === "SKIP" ? "○ SKIP" : "❌";
    text += `${icon} **Step ${step.step}: ${step.name}**\n`;
    text += `   ${step.detail}\n`;
    if (step.action) text += `   > **Action:** ${step.action}\n`;
    text += "\n";
  }

  if (!cascadeComplete) {
    text += `## Why This Is Blocking\n\n`;
    text += `The initialization cascade is the derivability gate (§4.3, §6.2 of the white paper).\n`;
    text += `A stateless agent given an incomplete artifact set fills missing context arbitrarily —\n`;
    text += `producing locally valid, architecturally incoherent output at generation speed.\n\n`;
    text += `Complete the failing steps before the first implementation session begins.\n`;
  } else {
    text += `## Cascade Complete\n\n`;
    text += `A stateless agent given these artifacts can derive any valid implementation state\n`;
    text += `without further human direction. The derivability criterion (§4.3) is satisfied.\n\n`;
    text += `**Suggested next step:** Use \`generate_session_prompt\` to produce a bound prompt\n`;
    text += `(specification references + scope + acceptance criteria) for each roadmap item.\n`;
  }

  const nextSteps = steps.filter((s) => s.action).map((s) => s.action!);
  text += `\n---\n`;
  text += `\`files_created\`: []\n`;
  text += `\`next_steps\`: ${JSON.stringify(nextSteps, null, 2)}\n`;
  return text;
}
