/**
 * refresh-output: Output formatting helpers for refresh_project.
 *
 * Contains project-specific.md management, content migration,
 * and all output-building functions for preview/applied modes.
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import yaml from "js-yaml";
import type { Tag, ContentTier, ForgeCraftConfig } from "../shared/types.js";
import type { composeTemplates } from "../registry/composer.js";
import type { CntDriftResult } from "../shared/cnt-health.js";
import type { DriftReport } from "./refresh-analyzer.js";

// ── Constants ────────────────────────────────────────────────────────

export const PROJECT_SPECIFIC_PLACEHOLDER = `# Project-Specific Rules
<!-- This file is owned by YOU. ForgeCraft will never overwrite it. -->
<!-- Add project-specific rules, framework choices, conventions, and custom corrections here. -->
<!-- The sentinel CLAUDE.md links here for any AI reading your project. -->

## Framework & Stack Choices
<!-- e.g. We use Prisma for ORM. Deploy target is Railway. -->

## Custom Corrections
<!-- Log corrections here so the AI learns from them. -->
<!-- Format: - YYYY-MM-DD: [description of correction] -->

## Project-Specific Gates
<!-- Add any quality rules specific to this project that don't belong in universal standards. -->
`;

// ── Project Specific File ────────────────────────────────────────────

/**
 * Ensures .claude/standards/project-specific.md exists.
 * Never overwrites an existing file — this file is user-owned.
 *
 * @param projectDir - Absolute path to project root
 */
export function ensureProjectSpecific(projectDir: string): void {
  const filePath = join(projectDir, ".claude", "standards", "project-specific.md");
  if (!existsSync(filePath)) {
    mkdirSync(dirname(filePath), { recursive: true });
    writeFileSync(filePath, PROJECT_SPECIFIC_PLACEHOLDER, "utf-8");
  }
}

/**
 * Migrates content from a large monolithic CLAUDE.md to project-specific.md.
 * Extracts sections that look like user-added content (not ForgeCraft template output).
 *
 * @param projectDir - Absolute path to project root
 * @param existingContent - Current CLAUDE.md content
 * @param isForgeCraftGenerated - Whether CLAUDE.md was generated by ForgeCraft
 * @returns Migration warning message for the user
 */
export function extractCustomContent(
  projectDir: string,
  existingContent: string,
  isForgeCraftGenerated: boolean,
): string {
  const projectSpecificPath = join(projectDir, ".claude", "standards", "project-specific.md");

  if (existsSync(projectSpecificPath)) {
    const existing = readFileSync(projectSpecificPath, "utf-8");
    if (!existing.includes(PROJECT_SPECIFIC_PLACEHOLDER.slice(0, 40))) {
      return isForgeCraftGenerated
        ? "Your existing CLAUDE.md was a ForgeCraft-generated monolithic file. It has been replaced with a sentinel. Custom content was NOT migrated because `.claude/standards/project-specific.md` already contains your edits."
        : "Your existing CLAUDE.md appears to be custom. It has been replaced with the sentinel. Back up any custom rules you need into `.claude/standards/project-specific.md`.";
    }
  }

  const forgecraftHeaders = new Set([
    "Code Standards", "Production Code Standards", "SOLID Principles",
    "Zero Hardcoded Values", "Zero Mocks in Application Code", "Interfaces First",
    "Dependency Injection", "Error Handling", "Modular from Day One",
    "Layered Architecture", "Clean Code Principles", "CI/CD", "Testing Pyramid",
    "Data Guardrails", "Commit Protocol", "MCP-Powered Tooling",
    "Engineering Preferences", "Library / Package Standards",
    "CLI Standards", "API Standards", "Security", "Graceful Shutdown", "Project Identity",
  ]);

  const lines = existingContent.split("\n");
  const customSections: string[] = [];
  let inCustomSection = false;
  let currentSection: string[] = [];

  for (const line of lines) {
    const headerMatch = line.match(/^#{1,3}\s+(.+)/);
    if (headerMatch) {
      if (inCustomSection && currentSection.length > 2) {
        customSections.push(currentSection.join("\n").trim());
      }
      const currentHeader = headerMatch[1].trim();
      inCustomSection = !Array.from(forgecraftHeaders).some((h) =>
        currentHeader.toLowerCase().includes(h.toLowerCase()),
      );
      currentSection = [line];
    } else {
      currentSection.push(line);
    }
  }
  if (inCustomSection && currentSection.length > 2) {
    customSections.push(currentSection.join("\n").trim());
  }

  if (customSections.length > 0) {
    const extracted = `# Project-Specific Rules\n<!-- Migrated from monolithic CLAUDE.md by ForgeCraft sentinel upgrade -->\n<!-- Review and clean up — some content below may have been incorrectly classified as custom -->\n\n${customSections.join("\n\n")}\n`;
    mkdirSync(dirname(projectSpecificPath), { recursive: true });
    writeFileSync(projectSpecificPath, extracted, "utf-8");
    return `Your CLAUDE.md (${existingContent.split("\n").length} lines) has been converted to a sentinel. ${customSections.length} custom section(s) were extracted to \`.claude/standards/project-specific.md\` — please review that file and clean it up.`;
  }

  ensureProjectSpecific(projectDir);
  return `Your CLAUDE.md (${existingContent.split("\n").length} lines) has been converted to a sentinel. No custom sections were detected. Review \`.claude/standards/project-specific.md\` and add any project-specific rules you need.`;
}

// ── Output Builders ──────────────────────────────────────────────────

/**
 * Output when no forgecraft.yaml exists.
 *
 * @param projectDir - Absolute path to project root
 * @returns No-config error message
 */
export function buildNoConfigOutput(projectDir: string): string {
  return (
    `# No Configuration Found\n\n` +
    `No forgecraft.yaml or .forgecraft.json found in \`${projectDir}\`.\n\n` +
    `Run setup first to initialize your project configuration:\n` +
    `  npx forgecraft-mcp setup ${projectDir}\n`
  );
}

/**
 * Build the preview (dry-run) output for proposed changes.
 *
 * @param drift - Drift report from analyzeDrift
 * @param updatedTags - Proposed updated tag set
 * @param _config - Updated config (unused but kept for signature symmetry)
 * @param composed - Composed template result
 * @param tier - Proposed tier
 * @returns Formatted preview text
 */
export function buildPreviewOutput(
  drift: DriftReport,
  updatedTags: Tag[],
  _config: ForgeCraftConfig,
  composed: ReturnType<typeof composeTemplates>,
  tier: ContentTier,
): string {
  let text = `# Refresh Preview\n\n`;
  text += `**Current Tags:** ${drift.currentTags.map((t) => `[${t}]`).join(" ")}\n`;
  text += `**Proposed Tags:** ${updatedTags.map((t) => `[${t}]`).join(" ")}\n`;
  text += `**Tier:** ${tier}\n\n`;

  if (drift.newTagSuggestions.length > 0) {
    text += `## New Tags Detected\n`;
    for (const s of drift.newTagSuggestions) {
      const marker = s.confidence >= 0.6 ? "✅ auto-add" : "💡 suggest";
      text += `- **[${s.tag}]** (${Math.round(s.confidence * 100)}%) — ${marker}: ${s.evidence.join(", ")}\n`;
    }
    text += "\n";
  }

  if (drift.droppedTagCandidates.length > 0) {
    text += `## Tags No Longer Detected\n`;
    text += `_These tags are in your config but not detected in code. Consider removing if no longer relevant._\n`;
    text += drift.droppedTagCandidates.map((t) => `- [${t}]`).join("\n");
    text += "\n\n";
  }

  if (drift.tierChange) {
    text += `## Tier Change\n${drift.tierChange.from} → ${drift.tierChange.to}\n\n`;
  }

  text += `## Content Impact\n`;
  text += `- Instruction blocks: ${drift.blockCountDelta.before} → ${drift.blockCountDelta.after}\n`;
  text += `- Total available: ${composed.instructionBlocks.length} blocks, ${composed.nfrBlocks.length} NFRs, ${composed.hooks.length} hooks, ${composed.skills.length} skills\n\n`;

  if (drift.completenessGaps.length > 0) {
    text += `## Remaining Gaps\n`;
    text += drift.completenessGaps.map((g) => `- ${g}`).join("\n");
    text += "\n\n";
  }

  text += `_Run with --apply to write changes: \`npx forgecraft-mcp refresh <project_dir> --apply\`_`;
  return text;
}

/**
 * Build the output after applying changes.
 *
 * @param drift - Drift report from analyzeDrift
 * @param updatedTags - Applied tag set
 * @param config - Updated ForgeCraft config
 * @param composed - Composed template result
 * @param tier - Applied tier
 * @param usedSentinel - Whether sentinel mode was used
 * @param migrationWarning - Optional migration warning message
 * @returns Formatted applied output text
 */
export function buildAppliedOutput(
  drift: DriftReport,
  updatedTags: Tag[],
  config: ForgeCraftConfig,
  composed: ReturnType<typeof composeTemplates>,
  tier: ContentTier,
  usedSentinel = true,
  migrationWarning?: string,
): string {
  const configYaml = yaml.dump(config, { lineWidth: 100, noRefs: true });

  let text = `# Project Refreshed\n\n`;
  text += `**Tags:** ${updatedTags.map((t) => `[${t}]`).join(" ")}\n`;
  text += `**Tier:** ${tier}\n\n`;

  text += `## Changes Applied\n`;
  text += `- forgecraft.yaml — updated\n`;
  if (usedSentinel) {
    text += `- CLAUDE.md — replaced with sentinel (~50 lines)\n`;
    text += `- .claude/standards/*.md — domain files generated (${composed.instructionBlocks.length} blocks distributed)\n`;
    text += `- .claude/standards/project-specific.md — preserved (user-owned, never overwritten)\n\n`;
  } else {
    text += `- Instruction files — regenerated (${composed.instructionBlocks.length} blocks)\n\n`;
  }

  if (migrationWarning) {
    text += `## Migration Notice\n${migrationWarning}\n\n`;
  }

  if (drift.newTagSuggestions.length > 0) {
    const added = drift.newTagSuggestions.filter((s) => s.confidence >= 0.6);
    if (added.length > 0) {
      text += `## New Tags Added\n`;
      text += added.map((s) => `- [${s.tag}] — ${s.evidence.join(", ")}`).join("\n");
      text += "\n\n";
    }
  }

  text += `## What refresh does NOT create\n`;
  text += `Run \`scaffold .\` (without --force) to create any missing artifacts:\n`;
  text += `Status.md, docs/PRD.md, docs/TechSpec.md, docs/adrs/, .env.example, hooks, skills, .gitignore\n\n`;

  text += `## Updated Config\n\`\`\`yaml\n${configYaml}\`\`\`\n\n`;
  text += `> **Tip:** Remove ForgeCraft from your MCP servers to save tokens (setup is done).\n`;
  text += `> Re-add it when needed: \`claude mcp add forgecraft -- npx -y forgecraft-mcp\`\n\n`;
  text += `⚠️ **Restart required** to pick up CLAUDE.md changes.`;
  return text;
}

/**
 * Format the CNT drift section for refresh output.
 *
 * @param drift - The CNT drift detection result
 * @returns Formatted section string (empty string if no CNT or no drift)
 */
export function formatCntDriftSection(drift: CntDriftResult): string {
  if (!drift.hasCnt) return "";

  const lines: string[] = ["", "## CNT Drift"];

  if (drift.staleNodes.length === 0 && drift.uncoveredModules.length === 0) {
    lines.push("✅ CNT tree is in sync with src/ modules.");
    return lines.join("\n");
  }

  if (drift.staleNodes.length > 0) {
    lines.push(`**Stale nodes** (no matching src/ module): ${drift.staleNodes.join(", ")}`);
  }

  if (drift.uncoveredModules.length > 0) {
    lines.push(`**Uncovered modules** (no CNT node): ${drift.uncoveredModules.join(", ")}`);
    lines.push(`Run \`cnt_add_node\` to add nodes for uncovered modules.`);
  }

  return lines.join("\n");
}
