/**
 * scaffold_project tool handler.
 *
 * Generates full project structure from classified tags.
 * Skips existing files by default to avoid overwriting user content.
 */

import { z } from "zod";
import { mkdirSync, chmodSync, existsSync, writeFileSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import yaml from "js-yaml";
import {
  ALL_TAGS,
  ALL_OUTPUT_TARGETS,
  OUTPUT_TARGET_CONFIGS,
  DEFAULT_OUTPUT_TARGET,
} from "../shared/types.js";
import type {
  Tag,
  ScaffoldResult,
  OutputTarget,
  ProjectDeploymentConfig,
  ForgeCraftConfig,
  CascadeDecision,
} from "../shared/types.js";
import {
  loadAllTemplatesWithExtras,
  loadUserOverrides,
} from "../registry/loader.js";
import { composeTemplates } from "../registry/composer.js";
import {
  renderInstructionFile,
  renderSkill,
  renderStatusMd,
  renderPrdSkeleton,
  renderTechSpecSkeleton,
} from "../registry/renderer.js";
import { renderSentinelTree } from "../registry/sentinel-renderer.js";
import { writeFileIfMissing, checkGitSafety } from "../shared/filesystem.js";
import { detectProjectContext } from "../analyzers/project-context.js";
import { createLogger } from "../shared/logger/index.js";
import { deriveDefaultCascadeDecisions } from "./cascade-defaults.js";

const logger = createLogger("tools/scaffold");

/** Template for the user-owned project-specific rules file. Never overwritten. */
const PROJECT_SPECIFIC_TEMPLATE = `# Project-Specific Rules
<!-- This file is owned by YOU. ForgeCraft will never overwrite it. -->
<!-- Add project-specific rules, framework choices, conventions, and corrections here. -->
<!-- The sentinel CLAUDE.md links here so any AI reading your project can find it. -->

## Framework & Stack Choices
<!-- e.g. We use Prisma for ORM. Deploy target is Railway. Python 3.11+. -->

## Custom Corrections Log
<!-- Log AI corrections so the pattern isn't repeated. -->
<!-- Format: - YYYY-MM-DD: [description of correction] -->

## Project-Specific Gates
<!-- Add quality rules specific to this project that don't belong in universal standards. -->
`;

/** Template for hook false-positive exceptions. Never overwritten once created. */
const EXCEPTIONS_TEMPLATE =
  JSON.stringify(
    {
      version: "1",
      _comment:
        "Hook false-positive exceptions. Add entries here to prevent rediscovering the same false positive each session. Each entry: {id, hook, pattern, reason, addedAt, addedBy, adr?}",
      exceptions: [],
    },
    null,
    2,
  ) + "\n";

/** Template for project-specific quality gates. Never overwritten once created. */
const PROJECT_GATES_TEMPLATE = `version: "1"
# Project-specific quality gates.
# Gates you discover while working that should be enforced for this project.
# Set generalizable: true + fill in evidence to contribute to the community registry.
# See: https://github.com/genspec-dev/quality-gates/issues/new?template=quality-gate-proposal.md
gates: []
`;

/** README stub for smoke tests directory. */
const SMOKE_TESTS_README = `# Smoke Tests

Generated by ForgeCraft scaffold. Fill in the critical paths from your tech spec.

## What smoke tests cover
- Every API entry point that serves real users
- Every critical user journey end-to-end
- Every DB migration (verify schema applied correctly)
- Every external integration handshake

## Format
Use the tool configured in forgecraft.yaml deployment.testing.smokeTool (or default to HTTP assertions).
All smoke tests must complete in < 60 seconds total.

## Running
See forgecraft.yaml tools.test or your project's test runner.
Results are written to .forgecraft/reports/smoke-latest.json.

## Required before deployment
All smoke tests must pass against staging before any production deploy.
See verification.yaml deployment-gates phase.
`;

/** README stub for load tests directory. */
const LOAD_TESTS_README = `# Load Tests

Generated by ForgeCraft scaffold. Fill in the parameters from your tech spec.

## Parameters (fill in from forgecraft.yaml deployment.testing.load)
- Concurrent users: [TODO: concurrentUsers from forgecraft.yaml]
- Target RPS: [TODO: targetRps from forgecraft.yaml]
- p99 ceiling: [TODO: p99CeilingMs ms]
- Duration: [TODO: durationSeconds seconds minimum]

## When these parameters are missing
Deploying without stated load test parameters is full deployment with manual monitoring.
The paper requires: parameters named in spec BEFORE the test runs, not after.
Add them to forgecraft.yaml deployment.testing.load before running.

## Tool
Use the tool configured in forgecraft.yaml deployment.testing.load.tool (k6, Artillery, Locust, etc.)
Results are written to .forgecraft/reports/load-latest.json.

## Required before pre-release
See verification.yaml pre-release-hardening phase, load-test step.
`;

/** Stub content for docs/use-cases.md. UNFILLED marker signals check-cascade to report STUB. */
const USE_CASES_STUB = `<!-- UNFILLED: Use Cases -->

# Use Cases

## UC-01: [Name]
**Actor**: <!-- FILL: who? -->
**Precondition**: <!-- FILL: what must be true before? -->
**Steps**: <!-- FILL: numbered steps -->
**Success**: <!-- FILL: what changed? -->

## UC-02: [Name]
<!-- FILL -->

## UC-03: [Name]
<!-- FILL -->
`;

/**
 * Build the UNFILLED stub content for docs/diagrams/c4-context.md.
 *
 * @param projectName - Human-readable project name for the diagram title
 * @returns Stub content with UNFILLED markers
 */
function buildC4ContextStub(projectName: string): string {
  return `<!-- UNFILLED: C4 Context Diagram -->
<!-- Run \`forgecraft generate_diagram\` to auto-generate from your spec -->

# System Context Diagram

\`\`\`mermaid
C4Context
  title System Context: ${projectName}
  Person(user, "User", "<!-- FILL: Who uses the system? -->")
  System(system, "${projectName}", "<!-- FILL: What does the system do in one sentence? -->")
  Rel(user, system, "<!-- FILL: Primary interaction -->")
\`\`\`
`;
}

/**
 * Write a spec stub file. Only creates when the file does not exist, or when
 * force=true AND the existing file still contains the UNFILLED marker (meaning
 * the user has not yet filled it in).
 *
 * @param relativePath - Relative path for tracking output
 * @param fullPath - Absolute path to write
 * @param content - Stub content to write
 * @param force - Whether to overwrite existing stubs
 * @param filesCreated - Mutable array to append created paths to
 * @param filesSkipped - Mutable array to append skipped paths to
 */
function writeSpecStub(
  relativePath: string,
  fullPath: string,
  content: string,
  force: boolean,
  filesCreated: string[],
  filesSkipped: string[],
): void {
  mkdirSync(dirname(fullPath), { recursive: true });

  if (!existsSync(fullPath)) {
    writeFileSync(fullPath, content, "utf-8");
    filesCreated.push(relativePath);
    return;
  }

  const existing = readFileSync(fullPath, "utf-8");
  if (force && existing.includes("<!-- UNFILLED")) {
    writeFileSync(fullPath, content, "utf-8");
    filesCreated.push(relativePath);
  } else {
    filesSkipped.push(relativePath);
  }
}

// ── Schema ───────────────────────────────────────────────────────────

export const scaffoldProjectSchema = z.object({
  tags: z
    .array(z.enum(ALL_TAGS as unknown as [string, ...string[]]))
    .min(1)
    .describe("Project classification tags. UNIVERSAL is always included."),
  project_dir: z
    .string()
    .describe("Absolute path to the project root directory."),
  project_name: z.string().describe("Human-readable project name."),
  language: z
    .enum(["typescript", "python"])
    .default("typescript")
    .describe("Primary programming language."),
  dry_run: z
    .boolean()
    .default(false)
    .describe("If true, return the plan without writing files."),
  force: z
    .boolean()
    .default(false)
    .describe(
      "If true, overwrite existing files. Default: skip files that already exist.",
    ),
  output_targets: z
    .array(z.enum(ALL_OUTPUT_TARGETS as unknown as [string, ...string[]]))
    .default(["claude"])
    .describe(
      "AI assistant targets to generate instruction files for. Options: claude, cursor, copilot, windsurf, cline, aider.",
    ),
  sentinel: z
    .boolean()
    .default(true)
    .describe(
      "If true (default), generate a 50-line sentinel CLAUDE.md + .claude/standards/ domain files instead of one large file. Set to false to generate the traditional monolithic CLAUDE.md.",
    ),
});

// ── Handler ──────────────────────────────────────────────────────────

export async function scaffoldProjectHandler(
  args: z.infer<typeof scaffoldProjectSchema>,
): Promise<{ content: Array<{ type: "text"; text: string }> }> {
  const tags: Tag[] = args.tags.includes("UNIVERSAL")
    ? (args.tags as Tag[])
    : (["UNIVERSAL", ...args.tags] as Tag[]);

  logger.info("Scaffolding project", {
    tags,
    projectDir: args.project_dir,
    dryRun: args.dry_run,
    force: args.force,
  });

  // Load and compose templates (respects forgecraft.yaml config if present)
  const userConfig = loadUserOverrides(args.project_dir);
  const templateSets = await loadAllTemplatesWithExtras(
    undefined,
    userConfig?.templateDirs,
  );
  const composed = composeTemplates(tags, templateSets, {
    config: userConfig ?? undefined,
  });

  const context = detectProjectContext(
    args.project_dir,
    args.project_name,
    args.language,
    tags,
  );

  // Render content
  const outputTargets = (args.output_targets ?? [
    DEFAULT_OUTPUT_TARGET,
  ]) as OutputTarget[];
  const statusMdContent = renderStatusMd(context);
  const prdContent = renderPrdSkeleton(context);
  const techSpecContent = renderTechSpecSkeleton(context);

  if (args.dry_run) {
    const plan = buildDryRunPlan(composed, tags);
    return { content: [{ type: "text", text: plan }] };
  }

  // Check git safety
  const gitWarning = checkGitSafety(args.project_dir);

  const filesCreated: string[] = [];
  const filesSkipped: string[] = [];

  /** Track a safe write result. */
  function trackWrite(
    relativePath: string,
    filePath: string,
    content: string,
  ): void {
    const result = writeFileIfMissing(filePath, content, args.force);
    if (result === "skipped") {
      filesSkipped.push(relativePath);
    } else {
      filesCreated.push(relativePath);
    }
  }

  // Create directories from structure entries
  for (const entry of composed.structureEntries) {
    const fullPath = join(args.project_dir, entry.path);
    if (entry.type === "directory") {
      mkdirSync(fullPath, { recursive: true });
      filesCreated.push(`${entry.path}/`);
    }
  }

  // Write instruction files for all output targets
  for (const target of outputTargets) {
    const targetConfig = OUTPUT_TARGET_CONFIGS[target];

    // For claude target: use sentinel tree (default) or monolithic file
    if (target === "claude" && args.sentinel !== false) {
      const sentinelFiles = renderSentinelTree(
        composed.instructionBlocks,
        context,
      );
      for (const file of sentinelFiles) {
        const fullPath = join(args.project_dir, file.relativePath);
        mkdirSync(dirname(fullPath), { recursive: true });
        trackWrite(file.relativePath, fullPath, file.content);
      }
      // Scaffold the user-owned project-specific.md (never overwritten after first creation)
      const projectSpecificPath = join(
        args.project_dir,
        ".claude",
        "standards",
        "project-specific.md",
      );
      trackWrite(
        ".claude/standards/project-specific.md",
        projectSpecificPath,
        PROJECT_SPECIFIC_TEMPLATE,
      );
    } else {
      const content = renderInstructionFile(
        composed.instructionBlocks,
        context,
        target,
        { compact: userConfig?.compact },
      );
      const outputPath = targetConfig.directory
        ? join(args.project_dir, targetConfig.directory, targetConfig.filename)
        : join(args.project_dir, targetConfig.filename);
      mkdirSync(dirname(outputPath), { recursive: true });
      const relativePath = targetConfig.directory
        ? `${targetConfig.directory}/${targetConfig.filename}`
        : targetConfig.filename;
      trackWrite(relativePath, outputPath, content);
    }
  }

  // Write Status.md
  trackWrite("Status.md", join(args.project_dir, "Status.md"), statusMdContent);

  // Write docs
  mkdirSync(join(args.project_dir, "docs"), { recursive: true });
  trackWrite(
    "docs/PRD.md",
    join(args.project_dir, "docs", "PRD.md"),
    prdContent,
  );
  trackWrite(
    "docs/TechSpec.md",
    join(args.project_dir, "docs", "TechSpec.md"),
    techSpecContent,
  );

  // Write spec stubs: cascade-detectable UNFILLED placeholders for the GS derivation funnel.
  // Never overwrite a file the user has already filled in (no <!-- UNFILLED marker).
  writeSpecStub(
    "docs/diagrams/c4-context.md",
    join(args.project_dir, "docs", "diagrams", "c4-context.md"),
    buildC4ContextStub(args.project_name),
    args.force,
    filesCreated,
    filesSkipped,
  );
  writeSpecStub(
    "docs/use-cases.md",
    join(args.project_dir, "docs", "use-cases.md"),
    USE_CASES_STUB,
    args.force,
    filesCreated,
    filesSkipped,
  );

  // Create docs/adrs/ with README so the directory is tracked by git and
  // the Auditable scorer finds it immediately (ADRs score 2/2 once populated).
  const adrsDir = join(args.project_dir, "docs", "adrs");
  mkdirSync(adrsDir, { recursive: true });
  trackWrite(
    "docs/adrs/README.md",
    join(adrsDir, "README.md"),
    renderAdrsReadme(context.projectName),
  );

  // Write .env.example — universal signals only; runtime-specific vars are added by the AI assistant
  trackWrite(
    ".env.example",
    join(args.project_dir, ".env.example"),
    "# Environment configuration\n# Copy to .env and fill in values\nLOG_LEVEL=info\n",
  );

  // Write hooks
  const hooksDir = join(args.project_dir, ".claude", "hooks");
  mkdirSync(hooksDir, { recursive: true });

  for (const hook of composed.hooks) {
    const hookPath = join(hooksDir, hook.filename);
    trackWrite(`.claude/hooks/${hook.filename}`, hookPath, hook.script);
    try {
      chmodSync(hookPath, 0o755);
    } catch {
      // chmod may fail on Windows, that's OK
    }
  }

  // Write skills (Claude Code custom commands)
  if (composed.skills.length > 0) {
    const commandsDir = join(args.project_dir, ".claude", "commands");
    mkdirSync(commandsDir, { recursive: true });

    for (const skill of composed.skills) {
      const skillContent = renderSkill(skill.content, context);
      const skillPath = join(commandsDir, skill.filename);
      trackWrite(`.claude/commands/${skill.filename}`, skillPath, skillContent);
    }
  }

  // Write .gitignore — content is language-aware; tool/framework choice is left to the team
  trackWrite(
    ".gitignore",
    join(args.project_dir, ".gitignore"),
    renderGitignore(args.language),
  );

  // Create .forgecraft/exceptions.json if it doesn't exist.
  // Version-controlled: it records architectural decisions about hook false positives.
  const forgecraftDir = join(args.project_dir, ".forgecraft");
  mkdirSync(forgecraftDir, { recursive: true });
  const exceptionsPath = join(forgecraftDir, "exceptions.json");
  if (!existsSync(exceptionsPath)) {
    writeFileSync(exceptionsPath, EXCEPTIONS_TEMPLATE, "utf-8");
    filesCreated.push(".forgecraft/exceptions.json");
  } else {
    filesSkipped.push(".forgecraft/exceptions.json");
  }

  const projectGatesPath = join(forgecraftDir, "project-gates.yaml");
  if (!existsSync(projectGatesPath)) {
    writeFileSync(projectGatesPath, PROJECT_GATES_TEMPLATE, "utf-8");
    filesCreated.push(".forgecraft/project-gates.yaml");
  } else {
    filesSkipped.push(".forgecraft/project-gates.yaml");
  }

  // If deployment config is present, scaffold smoke/load test stubs and reports dir.
  if (userConfig?.deployment) {
    const smokeDir = join(args.project_dir, "tests", "smoke");
    const loadDir = join(args.project_dir, "tests", "load");
    const reportsDir = join(args.project_dir, ".forgecraft", "reports");
    mkdirSync(smokeDir, { recursive: true });
    mkdirSync(loadDir, { recursive: true });
    mkdirSync(reportsDir, { recursive: true });
    trackWrite(
      "tests/smoke/README.md",
      join(smokeDir, "README.md"),
      renderSmokeTestsReadme(userConfig.deployment),
    );
    trackWrite(
      "tests/load/README.md",
      join(loadDir, "README.md"),
      renderLoadTestsReadme(userConfig.deployment),
    );
    trackWrite(
      ".forgecraft/reports/.gitkeep",
      join(reportsDir, ".gitkeep"),
      "",
    );
  }

  // ── Step 0: Write cascade decisions to forgecraft.yaml ─────────────────
  const cascadeDecisions = writeCascadeDecisions(args.project_dir, tags, args.project_name, userConfig);

  const result: ScaffoldResult = {
    filesCreated,
    mcpServersConfigured: [],
    nextSteps: [
      "Review and adjust instruction files for your project specifics",
      "Fill in docs/PRD.md with your actual requirements",
      "Fill in docs/TechSpec.md with your architecture decisions",
      renderInstallStep(args.language),
      "Start implementing your first feature module",
    ],
    restartRequired: true,
  };

  let text = `# Project Scaffolded Successfully\n\n`;
  text += `**Tags:** ${tags.map((t) => `[${t}]`).join(" ")}\n`;
  text += `**Files Created:** ${filesCreated.length}\n\n`;

  if (gitWarning) {
    text += `\n> ⚠️ **Git Warning:** ${gitWarning}\n\n`;
  }

  text += `## Created Files\n`;
  text += filesCreated.map((f) => `- \`${f}\``).join("\n");

  if (filesSkipped.length > 0) {
    text += `\n\n## Skipped (already exist)\n`;
    text += filesSkipped.map((f) => `- \`${f}\``).join("\n");
    text += `\n\n_Use \`force=true\` to overwrite existing files._`;
  }

  text += `\n\n## Next Steps\n`;
  text += result.nextSteps.map((s, i) => `${i + 1}. ${s}`).join("\n");
  text += renderGsDisclosure();
  text += renderCascadeDecisionsSection(cascadeDecisions);
  text += `\n\n⚠️ **Restart may be required** to pick up instruction files and hooks.`;

  return { content: [{ type: "text", text }] };
}

// ── Cascade Decisions (Step 0) ────────────────────────────────────────

/** Canonical artifact path for each cascade step (for display). */
const STEP_ARTIFACT_DISPLAY: Record<string, string> = {
  functional_spec: "PRD.md",
  architecture_diagrams: "c4-context.md",
  constitution: "CLAUDE.md",
  adrs: "docs/adrs/",
  behavioral_contracts: "use-cases.md",
};

/**
 * Write cascade.steps to forgecraft.yaml in the project directory.
 * Never overwrites existing decisions — only writes when cascade.steps is absent.
 *
 * @param projectDir - Absolute project root path
 * @param tags - Project tags used for deriving defaults
 * @param projectName - Human-readable project name
 * @param existingConfig - Already-loaded user config (avoids double-read)
 * @returns The cascade decisions that were written (or already existed)
 */
function writeCascadeDecisions(
  projectDir: string,
  tags: readonly Tag[],
  projectName: string,
  existingConfig: ForgeCraftConfig | null,
): CascadeDecision[] {
  const yamlPath = join(projectDir, "forgecraft.yaml");

  const existing = existingConfig?.cascade?.steps;
  if (existing && existing.length > 0) {
    return existing as CascadeDecision[];
  }

  const decisions = deriveDefaultCascadeDecisions(tags, projectName);

  const configBase: Record<string, unknown> = existingConfig
    ? (existingConfig as unknown as Record<string, unknown>)
    : { projectName, tags: [...tags] };

  const updated = { ...configBase, cascade: { steps: decisions } };
  writeFileSync(yamlPath, yaml.dump(updated, { lineWidth: 120 }), "utf-8");

  return decisions;
}

/**
 * Render the Cascade Decisions (Step 0) section for the scaffold output.
 *
 * @param decisions - The cascade decisions to display
 * @returns Formatted Markdown section
 */
function renderCascadeDecisionsSection(decisions: readonly CascadeDecision[]): string {
  let text = `\n\n## Cascade Decisions (Step 0)\n\n`;
  text += `The following spec artifacts have been assessed for this project:\n\n`;

  for (const decision of decisions) {
    const icon = decision.required ? "✓" : "○";
    const artifact = STEP_ARTIFACT_DISPLAY[decision.step] ?? decision.step;
    const label = decision.required ? `required (${artifact})` : `optional — ${decision.rationale.split(".")[0]}`;
    text += `  ${icon} ${decision.step} — ${label}\n`;
  }

  text += `\nReview these decisions. To revise: use \`set_cascade_requirement\` or edit\n`;
  text += `forgecraft.yaml under \`cascade.steps\`. These decisions determine which\n`;
  text += `artifacts are gated before implementation can begin.\n`;
  return text;
}

/**
 * Build a dry-run plan without writing files.
 */
function buildDryRunPlan(
  composed: ReturnType<typeof composeTemplates>,
  tags: Tag[],
): string {
  let text = `# Scaffold Plan (Dry Run)\n\n`;
  text += `**Tags:** ${tags.map((t) => `[${t}]`).join(" ")}\n\n`;

  text += `## Directories to Create\n`;
  const dirs = composed.structureEntries.filter((e) => e.type === "directory");
  text += dirs
    .map((d) => `- \`${d.path}/\`${d.description ? ` — ${d.description}` : ""}`)
    .join("\n");

  text += `\n\n## Files to Generate\n`;
  text += `- CLAUDE.md (~50-line sentinel)\n`;
  text += `- .claude/standards/*.md (domain files — ForgeCraft-managed)\n`;
  text += `- .claude/standards/project-specific.md (YOUR file — ForgeCraft never overwrites)\n`;
  text += `- Status.md\n`;
  text += `- docs/PRD.md (skeleton)\n`;
  text += `- docs/TechSpec.md (skeleton with ${composed.nfrBlocks.length} NFR sections)\n`;
  text += `- docs/adrs/README.md (ADR directory bootstrap — Auditable signal)\n`;
  text += `- .env.example\n`;
  text += `- .gitignore\n`;

  text += `\n## Hooks to Install (${composed.hooks.length})\n`;
  text += composed.hooks
    .map((h) => `- \`${h.filename}\` (${h.trigger}) — ${h.description}`)
    .join("\n");

  if (composed.skills.length > 0) {
    text += `\n\n## Skills to Install (${composed.skills.length})\n`;
    text += composed.skills
      .map(
        (s) =>
          `- \`/project:${s.filename.replace(".md", "")}\` — ${s.description}`,
      )
      .join("\n");
  }

  text += `\n\n_Run again with dry_run=false to write files._`;
  return text;
}

/**
 * Render the bootstrap README for docs/adrs/.
 * Its presence tells the Auditable scorer that the ADR convention is adopted.
 * The first real ADR should supersede this file's instructions.
 */
function renderAdrsReadme(projectName: string): string {
  return [
    `# Architecture Decision Records — ${projectName}`,
    ``,
    `This directory contains Architecture Decision Records (ADRs) for ${projectName}.`,
    ``,
    `## Format`,
    ``,
    `Each ADR is a numbered Markdown file: \`NNNN-short-title.md\``,
    ``,
    `Use \`npx forgecraft-mcp generate_adr\` (or the \`generate_adr\` MCP action) to create a new ADR`,
    `with automatic sequencing and the standard MADR template.`,
    ``,
    `## Status values`,
    ``,
    `- **Proposed** — under discussion`,
    `- **Accepted** — decision taken, implementation may be pending`,
    `- **Superseded by ADR-NNNN** — replaced by a later decision`,
    `- **Deprecated** — no longer relevant`,
    ``,
    `## Why ADRs?`,
    ``,
    `Every non-obvious architectural choice must be recorded with context, alternatives`,
    `considered, and consequences accepted. Without this record, the team re-litigates`,
    `the same decisions and AI coding assistants cannot reason about past choices.`,
    ``,
    `---`,
    `_This README was generated by ForgeCraft scaffold. Replace it with your first ADR._`,
  ].join("\n");
}

/**
 * Language-aware .gitignore content.
 * Tool and framework choices (bundler output dirs, virtual envs, etc.) are left to the team;
 * only universal and language-level patterns are included.
 */
function renderGitignore(language: "typescript" | "python"): string {
  const universal = [".env", ".env.*", "coverage/", "*.log", ".DS_Store"];
  const byLanguage: Record<string, string[]> = {
    typescript: ["node_modules/", "dist/", "build/", ".tsbuildinfo"],
    python: [
      "__pycache__/",
      "*.pyc",
      ".venv/",
      "venv/",
      "dist/",
      "*.egg-info/",
      ".mypy_cache/",
    ],
  };
  return [...(byLanguage[language] ?? []), ...universal].join("\n") + "\n";
}

/**
 * Language-aware install step for next-steps guidance.
 * Intentionally vague — the AI assistant will choose the actual package manager.
 */
function renderInstallStep(language: "typescript" | "python"): string {
  const hints: Record<string, string> = {
    typescript: "Install dependencies (npm install / pnpm install / yarn)",
    python:
      "Create a virtual environment and install dependencies (pip install -e . / poetry install / uv sync)",
  };
  return hints[language] ?? "Install project dependencies";
}

/**
 * GS-model disclosure appended to every scaffold summary.
 *
 * Explains what was NOT generated and WHY — referencing the Generative Specification
 * white paper decisions so the team understands the design intent, not just the output.
 */
function renderGsDisclosure(): string {
  return [
    ``,
    ``,
    `## GS Model Disclosure`,
    ``,
    `ForgeCraft scaffolds to the **Generative Specification** model (7 properties, max 14 pts).`,
    `The following artifacts were intentionally NOT generated — here is the reasoning:`,
    ``,
    `| Artifact | Why not generated | GS property | How to satisfy it |`,
    `|---|---|---|---|`,
    `| commitlint / lefthook / husky | **Auditable(2/2)** requires commit discipline, not a specific tool. The GS model is tool-agnostic; enforce via any hook framework or CI rule. | Auditable | Add your preferred commit-lint config; \`verify\` will detect it automatically. |`,
    `| Linter config (.eslintrc, .pylintrc…) | **Defended(2/2)** requires a pre-commit hook + lint config, but which linter is a team/language decision the AI assistant should make from your spec. | Defended | Any recognized lint config file satisfies this signal. |`,
    `| CI pipeline file | **Executable(2/2)** is highest with CI evidence, but the pipeline syntax is platform-specific. The AI assistant generates this from your tag set. | Executable | Run \`scaffold\` then ask your AI to generate a CI workflow for your platform. |`,
    `| docs/PRD.md content | The skeleton is scaffolded; actual requirements are your inputs. | Self-Describing | Fill in PRD.md — it is referenced by the Self-Describing scorer. |`,
    ``,
    `> **GS principle:** scaffold outputs are language- and tool-agnostic starting points.`,
    `> The AI coding assistant fills in the specifics from your spec and tag context.`,
    `> Run \`node forgecraft-mcp/dist/index.js verify .\` at any time to see your GS score.`,
  ].join("\n");
}

/**
 * Render smoke tests README, substituting deployment config values where available.
 */
function renderSmokeTestsReadme(deployment: ProjectDeploymentConfig): string {
  const smokeTool =
    deployment.testing?.smokeTool ??
    "[TODO: set smokeTool in forgecraft.yaml deployment.testing]";
  return SMOKE_TESTS_README.replace(
    "deployment.testing.smokeTool (or default to HTTP assertions)",
    `deployment.testing.smokeTool: ${smokeTool}`,
  );
}

/**
 * Render load tests README, substituting deployment config values where available.
 */
function renderLoadTestsReadme(deployment: ProjectDeploymentConfig): string {
  const load = deployment.testing?.load;
  let readme = LOAD_TESTS_README;
  if (load?.concurrentUsers !== undefined) {
    readme = readme.replace(
      "[TODO: concurrentUsers from forgecraft.yaml]",
      String(load.concurrentUsers),
    );
  }
  if (load?.targetRps !== undefined) {
    readme = readme.replace(
      "[TODO: targetRps from forgecraft.yaml]",
      String(load.targetRps),
    );
  }
  if (load?.p99CeilingMs !== undefined) {
    readme = readme.replace(
      "[TODO: p99CeilingMs ms]",
      `${load.p99CeilingMs}ms`,
    );
  }
  if (load?.durationSeconds !== undefined) {
    readme = readme.replace(
      "[TODO: durationSeconds seconds minimum]",
      `${load.durationSeconds} seconds`,
    );
  }
  const tool =
    load?.tool ?? "[TODO: set deployment.testing.load.tool in forgecraft.yaml]";
  readme = readme.replace(
    "deployment.testing.load.tool (k6, Artillery, Locust, etc.)",
    `deployment.testing.load.tool: ${tool}`,
  );
  return readme;
}
