/**
 * scaffold-templates: Static template strings and render functions for scaffold_project.
 */

import type { ProjectDeploymentConfig } from "../shared/types.js";

export const PROJECT_SPECIFIC_TEMPLATE = `# Project-Specific Rules
<!-- This file is owned by YOU. ForgeCraft will never overwrite it. -->
<!-- Add project-specific rules, framework choices, conventions, and corrections here. -->
<!-- The sentinel CLAUDE.md links here so any AI reading your project can find it. -->

## Framework & Stack Choices
<!-- e.g. We use Prisma for ORM. Deploy target is Railway. Python 3.11+. -->

## Custom Corrections Log
<!-- Log AI corrections so the pattern isn't repeated. -->
<!-- Format: - YYYY-MM-DD: [description of correction] -->

## Project-Specific Gates
<!-- Add quality rules specific to this project that don't belong in universal standards. -->
`;

export const EXCEPTIONS_TEMPLATE =
  JSON.stringify(
    {
      version: "1",
      _comment:
        "Hook false-positive exceptions. Add entries here to prevent rediscovering the same false positive each session. Each entry: {id, hook, pattern, reason, addedAt, addedBy, adr?}",
      exceptions: [],
    },
    null,
    2,
  ) + "\n";

export const PROJECT_GATES_TEMPLATE = `version: "1"
# Project-specific quality gates.
# Gates you discover while working that should be enforced for this project.
# Set generalizable: true + fill in evidence to contribute to the community registry.
# See: https://github.com/jghiringhelli/quality-gates/issues/new?template=quality-gate-proposal.md
gates: []
`;

export const SMOKE_TESTS_README = `# Smoke Tests

Generated by ForgeCraft scaffold. Fill in the critical paths from your tech spec.

## What smoke tests cover
- Every API entry point that serves real users
- Every critical user journey end-to-end
- Every DB migration (verify schema applied correctly)
- Every external integration handshake

## Format
Use the tool configured in forgecraft.yaml deployment.testing.smokeTool (or default to HTTP assertions).
All smoke tests must complete in < 60 seconds total.

## Running
See forgecraft.yaml tools.test or your project's test runner.
Results are written to .forgecraft/reports/smoke-latest.json.

## Required before deployment
All smoke tests must pass against staging before any production deploy.
See verification.yaml deployment-gates phase.
`;

export const LOAD_TESTS_README = `# Load Tests

Generated by ForgeCraft scaffold. Fill in the parameters from your tech spec.

## Parameters (fill in from forgecraft.yaml deployment.testing.load)
- Concurrent users: [TODO: concurrentUsers from forgecraft.yaml]
- Target RPS: [TODO: targetRps from forgecraft.yaml]
- p99 ceiling: [TODO: p99CeilingMs ms]
- Duration: [TODO: durationSeconds seconds minimum]

## When these parameters are missing
Deploying without stated load test parameters is full deployment with manual monitoring.
The paper requires: parameters named in spec BEFORE the test runs, not after.
Add them to forgecraft.yaml deployment.testing.load before running.

## Tool
Use the tool configured in forgecraft.yaml deployment.testing.load.tool (k6, Artillery, Locust, etc.)
Results are written to .forgecraft/reports/load-latest.json.

## Required before pre-release
See verification.yaml pre-release-hardening phase, load-test step.
`;

/**
 * Render the bootstrap README for docs/adrs/.
 *
 * @param projectName - Human-readable project name
 * @returns README content string
 */
export function renderAdrsReadme(projectName: string): string {
  return [
    `# Architecture Decision Records — ${projectName}`,
    ``,
    `This directory contains Architecture Decision Records (ADRs) for ${projectName}.`,
    ``,
    `## Format`,
    ``,
    `Each ADR is a numbered Markdown file: \`NNNN-short-title.md\``,
    ``,
    `Use \`npx forgecraft-mcp generate_adr\` (or the \`generate_adr\` MCP action) to create a new ADR`,
    `with automatic sequencing and the standard MADR template.`,
    ``,
    `## Status values`,
    ``,
    `- **Proposed** — under discussion`,
    `- **Accepted** — decision taken, implementation may be pending`,
    `- **Superseded by ADR-NNNN** — replaced by a later decision`,
    `- **Deprecated** — no longer relevant`,
    ``,
    `## Why ADRs?`,
    ``,
    `Every non-obvious architectural choice must be recorded with context, alternatives`,
    `considered, and consequences accepted. Without this record, the team re-litigates`,
    `the same decisions and AI coding assistants cannot reason about past choices.`,
    ``,
    `---`,
    `_This README was generated by ForgeCraft scaffold. Replace it with your first ADR._`,
  ].join("\n");
}

/**
 * Language-aware .gitignore content.
 *
 * @param language - Primary project language
 * @returns .gitignore file content
 */
export function renderGitignore(language: "typescript" | "python"): string {
  const universal = [".env", ".env.*", "coverage/", "*.log", ".DS_Store"];
  const byLanguage: Record<string, string[]> = {
    typescript: ["node_modules/", "dist/", "build/", ".tsbuildinfo"],
    python: [
      "__pycache__/",
      "*.pyc",
      ".venv/",
      "venv/",
      "dist/",
      "*.egg-info/",
      ".mypy_cache/",
    ],
  };
  return [...(byLanguage[language] ?? []), ...universal].join("\n") + "\n";
}

/**
 * Language-aware install step for next-steps guidance.
 *
 * @param language - Primary project language
 * @returns Install step hint string
 */
export function renderInstallStep(language: "typescript" | "python"): string {
  const hints: Record<string, string> = {
    typescript: "Install dependencies (npm install / pnpm install / yarn)",
    python:
      "Create a virtual environment and install dependencies (pip install -e . / poetry install / uv sync)",
  };
  return hints[language] ?? "Install project dependencies";
}

/**
 * GS-model disclosure appended to every scaffold summary.
 *
 * @returns Formatted disclosure section
 */
export function renderGsDisclosure(): string {
  return [
    ``,
    ``,
    `## GS Model Disclosure`,
    ``,
    `ForgeCraft scaffolds to the **Generative Specification** model (7 properties, max 14 pts).`,
    `The following artifacts were intentionally NOT generated — here is the reasoning:`,
    ``,
    `| Artifact | Why not generated | GS property | How to satisfy it |`,
    `|---|---|---|---|`,
    `| commitlint / lefthook / husky | **Auditable(2/2)** requires commit discipline, not a specific tool. The GS model is tool-agnostic; enforce via any hook framework or CI rule. | Auditable | Add your preferred commit-lint config; \`verify\` will detect it automatically. |`,
    `| Linter config (.eslintrc, .pylintrc…) | **Defended(2/2)** requires a pre-commit hook + lint config, but which linter is a team/language decision the AI assistant should make from your spec. | Defended | Any recognized lint config file satisfies this signal. |`,
    `| CI pipeline file | **Executable(2/2)** is highest with CI evidence, but the pipeline syntax is platform-specific. The AI assistant generates this from your tag set. | Executable | Run \`scaffold\` then ask your AI to generate a CI workflow for your platform. |`,
    `| docs/PRD.md content | The skeleton is scaffolded; actual requirements are your inputs. | Self-Describing | Fill in PRD.md — it is referenced by the Self-Describing scorer. |`,
    ``,
    `> **GS principle:** scaffold outputs are language- and tool-agnostic starting points.`,
    `> The AI coding assistant fills in the specifics from your spec and tag context.`,
    `> Run \`node forgecraft-mcp/dist/index.js verify .\` at any time to see your GS score.`,
  ].join("\n");
}

/**
 * Render smoke tests README, substituting deployment config values.
 *
 * @param deployment - Project deployment configuration
 * @returns README content string
 */
export function renderSmokeTestsReadme(
  deployment: ProjectDeploymentConfig,
): string {
  const smokeTool =
    deployment.testing?.smokeTool ??
    "[TODO: set smokeTool in forgecraft.yaml deployment.testing]";
  return SMOKE_TESTS_README.replace(
    "deployment.testing.smokeTool (or default to HTTP assertions)",
    `deployment.testing.smokeTool: ${smokeTool}`,
  );
}

/**
 * Render load tests README, substituting deployment config values.
 *
 * @param deployment - Project deployment configuration
 * @returns README content string
 */
export function renderLoadTestsReadme(
  deployment: ProjectDeploymentConfig,
): string {
  const load = deployment.testing?.load;
  let readme = LOAD_TESTS_README;
  if (load?.concurrentUsers !== undefined)
    readme = readme.replace(
      "[TODO: concurrentUsers from forgecraft.yaml]",
      String(load.concurrentUsers),
    );
  if (load?.targetRps !== undefined)
    readme = readme.replace(
      "[TODO: targetRps from forgecraft.yaml]",
      String(load.targetRps),
    );
  if (load?.p99CeilingMs !== undefined)
    readme = readme.replace(
      "[TODO: p99CeilingMs ms]",
      `${load.p99CeilingMs}ms`,
    );
  if (load?.durationSeconds !== undefined)
    readme = readme.replace(
      "[TODO: durationSeconds seconds minimum]",
      `${load.durationSeconds} seconds`,
    );
  const tool =
    load?.tool ?? "[TODO: set deployment.testing.load.tool in forgecraft.yaml]";
  readme = readme.replace(
    "deployment.testing.load.tool (k6, Artillery, Locust, etc.)",
    `deployment.testing.load.tool: ${tool}`,
  );
  return readme;
}
