/**
 * setup_monitoring tool handler.
 *
 * Generates docs/monitoring-spec.md from the project's NFR contracts and
 * behavioral contracts. This is the production contract that forgecraft-eye
 * evaluates runtime signals against at T4.
 *
 * The generated spec contains:
 *   - Exception classes that signal specification drift
 *   - Alert thresholds with exact numeric criteria
 *   - SLO definitions for each service
 *   - Correlation ID and PII redaction policy
 *   - Property violation mapping (exception → GS property → spec location)
 */

import { z } from "zod";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { ToolResult } from "../shared/types.js";

// ── Schema ───────────────────────────────────────────────────────────

export const setupMonitoringSchema = z.object({
  project_dir: z.string().describe("Absolute path to the project root."),
  project_name: z
    .string()
    .optional()
    .describe(
      "Project name for the spec header. Inferred from directory name if omitted.",
    ),
  force: z
    .boolean()
    .optional()
    .describe("Overwrite existing monitoring-spec.md. Default: false."),
});

export type SetupMonitoringInput = z.infer<typeof setupMonitoringSchema>;

// ── Source doc paths ─────────────────────────────────────────────────

const SOURCE_DOCS = [
  "docs/nfr-contracts.md",
  "docs/behavioral-contracts.md",
  "docs/use-cases.md",
  "docs/PRD.md",
] as const;

// ── Template ─────────────────────────────────────────────────────────

function buildMonitoringSpec(
  projectName: string,
  nfrContent: string | null,
  behavioralContent: string | null,
): string {
  const date = new Date().toISOString().slice(0, 10);

  const nfrSection = nfrContent ? extractNfrExceptionClasses(nfrContent) : null;

  return `# Monitoring Specification — ${projectName}
<!-- Generated by forgecraft setup_monitoring on ${date} -->
<!-- This document is the T4 production contract. -->
<!-- forgecraft-eye evaluates runtime signals against these definitions. -->
<!-- DO NOT state thresholds as "when errors are high" — use exact numeric criteria. -->

---

## 1. Exception Classes

Exception classes that signal specification drift. Only exceptions listed here
trigger T4 diagnostic evaluation — not all exceptions, not error volume.

| Exception Class | Severity | GS Property Violated | Spec Location | Chronicle Tag |
|---|---|---|---|---|
${nfrSection?.exceptionRows ?? "| TODO_ExceptionClass | critical | Verifiable | docs/behavioral-contracts.md#TODO | t4-signal |"}

**Instructions:** For each exception class:
1. State the fully-qualified class name (e.g., \`PaymentRetryExhaustedException\`)
2. Assign severity: \`critical\` (T4 immediate), \`warning\` (T4 batched), \`info\` (T4 aggregate)
3. Map to the GS property it violates: Verifiable, Auditable, Defended, Composable, etc.
4. Reference the exact use case postcondition or invariant in the spec

---

## 2. Alert Thresholds

SLO alert definitions with exact numeric criteria. Thresholds stated as
"when errors are high" are invalid — the diagnostic agent cannot act on them.

| Alert Name | Metric | Condition | Duration | Severity | NFR Source |
|---|---|---|---|---|---|
${nfrSection?.alertRows ?? "| error_rate_high | http_request_errors_total / http_requests_total | > 0.005 | 5m | page | NFR-TODO |"}

**Instructions:** Every threshold must be:
- Numeric (exact value, not "high" or "low")
- Time-bounded (window: 1m, 5m, 15m, 1h)
- Tied to an NFR contract identifier (NFR-01, NFR-02, etc.)

---

## 3. SLO Definitions

PromQL (or equivalent) queries for each service-level objective.

\`\`\`yaml
# Service: TODO_service_name
# NFR source: docs/nfr-contracts.md#TODO
slos:
  - id: availability
    query: "sum(rate(http_requests_total{job=\"TODO\",code!~\"5..\"}[5m])) / sum(rate(http_requests_total{job=\"TODO\"}[5m]))"
    threshold: 0.999
    operator: ">="
    window: "30d"
    alert_name: TODO_AvailabilityBreach

  - id: p95_latency
    query: "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"TODO\"}[5m])) by (le))"
    threshold: 0.5
    operator: "<="
    window: "1h"
    alert_name: TODO_LatencyBreach
\`\`\`

---

## 4. Correlation ID Schema

How requests are traced end-to-end through the system. Required for T4 diagnosis
to correlate an exception with its originating request context.

\`\`\`
Header: X-Correlation-ID
Format: UUID v4
Propagation: all outbound service calls, all log entries, all exception payloads
Example: X-Correlation-ID: 550e8400-e29b-41d4-a716-446655440000
\`\`\`

**Log format requirement:**
\`\`\`json
{
  "timestamp": "ISO-8601",
  "level": "ERROR|WARN|INFO",
  "correlation_id": "UUID",
  "service": "service-name",
  "exception_class": "FullyQualifiedExceptionClass",
  "message": "human-readable description",
  "spec_ref": "docs/behavioral-contracts.md#use-case-id"
}
\`\`\`

---

## 5. PII Redaction Policy

What must never appear in logs or exception payloads.

| Field Category | Examples | Action |
|---|---|---|
| Identity | email, full_name, national_id | Redact — replace with \`[REDACTED]\` |
| Authentication | password, token, API key | Never log |
| Financial | card number, account number | Mask — last 4 digits only |
| Medical | diagnosis, prescription | Redact |
| Location | GPS coordinates, IP address | Anonymize — country-level only |

**Implementation:** Redaction must happen at the logging layer, not downstream.
If a field appears unredacted in a log entry, it is a Defended property violation.

---

## 6. Property Violation Mapping

Maps production signals to the GS properties they violate. Used by forgecraft-eye
to classify diagnoses before writing to Chronicle.

| Exception Pattern | GS Property | Diagnosis Template |
|---|---|---|
| \`*RetryExhausted*\` | Verifiable | "Retry contract does not cover [exception context]. Update use case postcondition." |
| \`*AuthorizationFailed*\` | Defended | "Authorization invariant violated at [endpoint]. Verify boundary guard in spec." |
| \`*ValidationException*\` | Verifiable | "Input contract incomplete — [field] not covered by precondition." |
| \`*TimeoutException*\` | Verifiable | "Timeout contract missing for [service call]. Add NFR SLO threshold." |
| \`*NullPointer*\` \| \`*undefined*\` | Verifiable | "Null postcondition not stated — [component] assumes non-null without contract." |
| \`*SchemaValidation*\` | Self-describing | "Schema contract outdated — regenerate from current spec." |

---

## 7. T4 Signal Queue

forgecraft-eye writes signals to \`.forgecraft/t4-signals.json\`.
Run \`forgecraft check_t4\` at session start to surface pending spec updates.

\`\`\`json
{
  "signals": [
    {
      "id": "sig-YYYYMMDD-HHMMSS-001",
      "timestamp": "ISO-8601",
      "exception_class": "FullyQualifiedExceptionClass",
      "severity": "critical|warning|info",
      "gs_property": "Verifiable|Auditable|Defended|Composable|Executable|Self-describing|Bounded",
      "spec_ref": "docs/behavioral-contracts.md#use-case-id",
      "diagnosis": "Human-readable diagnosis text",
      "suggested_update": "Specific spec change recommendation",
      "status": "pending|acknowledged|resolved",
      "correlation_id": "UUID of originating request"
    }
  ]
}
\`\`\`

${behavioralContent ? "## 8. Source NFR Contracts\n\nExtracted from docs/nfr-contracts.md. Review for completeness.\n\n" + formatNfrSummary(behavioralContent) : ""}
---

*Generated by ForgeCraft T4 setup. Reviewed and extended by practitioner.*
*forgecraft-eye config: see \`.forgecraft/eye-config.yaml\`*
`;
}

// ── NFR extraction helpers ────────────────────────────────────────────

function extractNfrExceptionClasses(nfrContent: string): {
  exceptionRows: string;
  alertRows: string;
} {
  const lines = nfrContent.split("\n");

  // Look for existing exception class mentions
  const exceptionLines = lines.filter(
    (l) =>
      l.toLowerCase().includes("exception") ||
      l.toLowerCase().includes("error class") ||
      l.toLowerCase().includes("failure mode"),
  );

  // Look for threshold mentions
  const thresholdLines = lines.filter(
    (l) =>
      l.toLowerCase().includes("threshold") ||
      l.toLowerCase().includes("slo") ||
      l.toLowerCase().includes("availability") ||
      l.toLowerCase().includes("latency") ||
      (l.toLowerCase().includes("error") && l.match(/\d+%|\d+ms/)),
  );

  const exceptionRows =
    exceptionLines.length > 0
      ? exceptionLines
          .slice(0, 5)
          .map(
            (l) =>
              `| \`${l.trim().replace(/[|]/g, "\\|")}\` | critical | Verifiable | docs/behavioral-contracts.md#TODO | t4-signal |`,
          )
          .join("\n")
      : "| TODO_ExceptionClass | critical | Verifiable | docs/behavioral-contracts.md#TODO | t4-signal |";

  const alertRows =
    thresholdLines.length > 0
      ? thresholdLines
          .slice(0, 3)
          .map(
            (l) =>
              `| TODO_Alert | ${l.trim().replace(/[|]/g, "\\|")} | TODO_duration | warning | NFR-TODO |`,
          )
          .join("\n")
      : "| error_rate_high | http_request_errors_total / http_requests_total | > 0.005 | 5m | page | NFR-TODO |";

  return { exceptionRows, alertRows };
}

function formatNfrSummary(content: string): string {
  const lines = content.split("\n");
  const relevant = lines
    .filter(
      (l) =>
        l.startsWith("#") ||
        l.toLowerCase().includes("nfr") ||
        l.toLowerCase().includes("slo") ||
        l.toLowerCase().includes("threshold"),
    )
    .slice(0, 20);
  return (
    relevant.join("\n") + "\n\n*[See full file for complete NFR contracts]*\n"
  );
}

// ── Eye config scaffold ──────────────────────────────────────────────

/**
 * Write `.forgecraft/eye-config.yaml` with sensible defaults if absent.
 * Mirrors the shape of `EyeConfig` in forgecraft-eye without importing it.
 *
 * @param projectDir - Absolute path to the project root.
 * @param projectName - Display name used for the CloudWatch log group slug.
 * @returns `true` if the file was created, `false` if it already existed or errored.
 */
export function scaffoldEyeConfig(
  projectDir: string,
  projectName: string,
): boolean {
  const configPath = join(projectDir, ".forgecraft", "eye-config.yaml");
  if (existsSync(configPath)) return false;

  const slug = projectName.toLowerCase().replace(/\s+/g, "-");
  const yaml = [
    `# forgecraft-eye configuration — generated by forgecraft setup_monitoring`,
    `# See: https://github.com/jghiringhelli/forgecraft-eye`,
    ``,
    `project_name: "${projectName}"`,
    `project_dir: "${projectDir}"`,
    `monitoring_spec_path: docs/monitoring-spec.md`,
    `signal_queue_path: .forgecraft/t4-signals.json`,
    `environment: production`,
    `log_adapter: stdin    # options: stdin | cloudwatch`,
    ``,
    `# CloudWatch adapter — uncomment and set log_adapter: cloudwatch`,
    `# cloudwatch:`,
    `#   log_group_name: /aws/lambda/${slug}`,
    `#   region: us-east-1`,
    `#   filter_pattern: "?ERROR ?WARN ?Exception"`,
  ].join("\n");

  try {
    mkdirSync(join(projectDir, ".forgecraft"), { recursive: true });
    writeFileSync(configPath, yaml, "utf-8");
    return true;
  } catch {
    return false;
  }
}

// ── Handler ───────────────────────────────────────────────────────────

export async function setupMonitoringHandler(
  args: SetupMonitoringInput,
): Promise<ToolResult> {
  const projectDir = resolve(args.project_dir);
  const force = args.force ?? false;

  const projectName =
    args.project_name ?? projectDir.split(/[\\/]/).pop() ?? "Project";

  const outputPath = join(projectDir, "docs", "monitoring-spec.md");

  if (existsSync(outputPath) && !force) {
    return {
      content: [
        {
          type: "text",
          text: [
            "## Monitoring Spec Already Exists",
            "",
            `\`docs/monitoring-spec.md\` already exists at ${outputPath}.`,
            "Pass \`force: true\` to regenerate.",
            "",
            "Run \`forgecraft check_t4\` to surface pending T4 signals.",
          ].join("\n"),
        },
      ],
    };
  }

  // Read available source docs
  let nfrContent: string | null = null;
  let behavioralContent: string | null = null;
  const sourcesRead: string[] = [];

  for (const docPath of SOURCE_DOCS) {
    const fullPath = join(projectDir, docPath);
    if (existsSync(fullPath)) {
      try {
        const content = readFileSync(fullPath, "utf-8");
        if (docPath.includes("nfr")) {
          nfrContent = content;
          sourcesRead.push(docPath);
        } else if (docPath.includes("behavioral")) {
          behavioralContent = content;
          sourcesRead.push(docPath);
        }
      } catch {
        /* non-fatal — continue with template */
      }
    }
  }

  // Ensure docs/ exists
  try {
    mkdirSync(join(projectDir, "docs"), { recursive: true });
  } catch {
    /* already exists */
  }

  const spec = buildMonitoringSpec(projectName, nfrContent, behavioralContent);

  try {
    writeFileSync(outputPath, spec, "utf-8");
  } catch (err) {
    return {
      content: [
        {
          type: "text",
          text: `Error writing monitoring-spec.md: ${String(err)}`,
        },
      ],
    };
  }

  const eyeConfigCreated = scaffoldEyeConfig(projectDir, projectName);

  const lines: string[] = [
    "## Monitoring Spec Generated",
    "",
    `Generated: \`docs/monitoring-spec.md\``,
    ...(eyeConfigCreated
      ? [
          "Generated: `.forgecraft/eye-config.yaml` (forgecraft-eye adapter config)",
        ]
      : []),
    "",
  ];

  if (sourcesRead.length > 0) {
    lines.push(
      `Sources read: ${sourcesRead.map((s) => `\`${s}\``).join(", ")}`,
    );
    lines.push("");
  } else {
    lines.push(
      "⚠️  No NFR contracts found — spec generated from template.",
      "Add `docs/nfr-contracts.md` and re-run for project-specific thresholds.",
      "",
    );
  }

  lines.push(
    "## Required Next Steps",
    "",
    "The generated spec contains TODO placeholders. Before T4 is operational:",
    "",
    "1. **Fill exception classes** (Section 1) — list the specific exception classes",
    "   that indicate specification drift in your system. Map each to the GS property",
    "   it violates and the spec location that governs it.",
    "",
    "2. **State exact thresholds** (Section 2) — replace all TODO_threshold values",
    "   with numeric criteria. 'When errors are high' is not a valid threshold.",
    "",
    "3. **Add SLO queries** (Section 3) — replace TODO PromQL queries with actual",
    "   metric names from your observability stack.",
    "",
    "4. **Install forgecraft-eye** — the T4 diagnostic agent that evaluates production logs",
    "   against your monitoring spec and writes signals to the queue.",
    "   ```bash",
    "   npm install forgecraft-eye",
    "   # Pipe logs in production:",
    "   my-service 2>&1 | npx forgecraft-eye",
    "   # Or invoke programmatically:",
    "   # import { runEyeFromConfig } from 'forgecraft-eye';",
    "   # await runEyeFromConfig(projectDir);",
    "   ```",
    "   npm: https://www.npmjs.com/package/forgecraft-eye",
    "   Source: https://github.com/jghiringhelli/forgecraft-eye",
    "",
    "5. **Run `forgecraft check_t4`** at the start of each session to surface",
    "   pending T4 signals from the production queue.",
    "",
    "## T4 Architecture Summary",
    "",
    "```",
    "Production exception fires",
    "  → forgecraft-eye evaluates against monitoring-spec.md",
    "  → writes to .forgecraft/t4-signals.json",
    "  → next session: forgecraft check_t4 surfaces pending signals",
    "  → practitioner approves spec update",
    "  → AI derives fix from updated specification",
    "  → T2 verifies, T3 deploys",
    "```",
  );

  return { content: [{ type: "text", text: lines.join("\n") }] };
}
